<a href="https://colab.research.google.com/github/jdj40211/TallerAplicacionesAlgebra/blob/main/Ejercicio12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy.linalg import eig, matrix_power

# Matrices de adyacencia de los dígrafos del Ejemplo 12
A_D1 = np.array([[0, 1, 1, 0],
                 [1, 0, 1, 1],
                 [1, 0, 0, 1],
                 [0, 0, 1, 0]])

A_D2 = np.array([[0, 1, 0, 0, 1, 0],
                 [1, 0, 0, 1, 0, 1],
                 [0, 0, 0, 1, 0, 1],
                 [0, 0, 0, 0, 1, 0],
                 [1, 0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 1, 0]])

# Función para verificar diagonalización y calcular potencias
def analizar_matriz(matriz, nombre):

    valores_propios, vectores_propios = eig(matriz)

    if len(set(np.round(valores_propios, decimals=5))) == len(valores_propios):
        print(f"La matriz {nombre} es diagonalizable.")
    else:
        print(f"La matriz {nombre} NO es diagonalizable.")

    print(f"Valores propios de {nombre}: {valores_propios}")
    print(f"Vectores propios de {nombre}: \n{vectores_propios}\n")

    # Calcular A^20 y A^21
    A_20 = matrix_power(matriz, 20)
    A_21 = matrix_power(matriz, 21)

    print(f"{nombre}^20 =\n{A_20}\n")
    print(f"{nombre}^21 =\n{A_21}\n")
    print(f"Entrada (1,1) de {nombre}^20: {A_20[0, 0]}")
    print(f"Entrada (1,1) de {nombre}^21: {A_21[0, 0]}\n")

analizar_matriz(A_D1, "A_D1")
analizar_matriz(A_D2, "A_D2")


La matriz A_D1 es diagonalizable.
Valores propios de A_D1: [ 1.87938524e+00 -1.53208889e+00 -3.47296355e-01 -1.50274614e-16]
Vectores propios de A_D1: 
[[-5.77350269e-01  5.77350269e-01  5.77350269e-01 -7.07106781e-01]
 [-6.56538502e-01 -2.28013429e-01 -4.28525073e-01  4.98571317e-16]
 [-4.28525073e-01 -6.56538502e-01  2.28013429e-01 -4.07921987e-16]
 [-2.28013429e-01  4.28525073e-01 -6.56538502e-01  7.07106781e-01]]

A_D1^20 =
[[102431  52497 134236 102431]
 [113887  61390 154928 113887]
 [ 72846  41041 102431  72846]
 [ 41041  20349  52497  41041]]

A_D1^21 =
[[186733 102431 257359 186733]
 [216318 113887 289164 216318]
 [143472  72846 186733 143472]
 [ 72846  41041 102431  72846]]

Entrada (1,1) de A_D1^20: 102431
Entrada (1,1) de A_D1^21: 186733

La matriz A_D2 NO es diagonalizable.
Valores propios de A_D2: [ 0.        +0.j          1.65289165+0.j         -1.65289165+0.j
  0.        +0.85559968j  0.        -0.85559968j  0.        +0.j        ]
Vectores propios de A_D2: 
[[ 0.000000