<a href="https://colab.research.google.com/github/jdj40211/TallerAplicacionesAlgebra/blob/main/Ejercicio10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Definir las matrices de adyacencia para G1, G2 y G3
A_G1 = np.array([[0, 1, 0, 1],
                 [1, 0, 1, 1],
                 [0, 1, 0, 1],
                 [1, 1, 1, 0]])

A_G2 = np.array([[0, 1, 0, 1, 0, 0],
                 [1, 0, 0, 1, 0, 0],
                 [0, 0, 0, 1, 1, 1],
                 [1, 1, 1, 0, 0, 0],
                 [0, 0, 1, 0, 0, 1],
                 [0, 0, 1, 0, 1, 0]])

A_G3 = np.array([[0, 1, 0, 1, 0, 0, 0, 1],
                 [1, 0, 0, 1, 0, 0, 0, 0],
                 [0, 0, 0, 1, 1, 1, 0, 1],
                 [1, 1, 1, 0, 0, 0, 1, 0],
                 [0, 0, 1, 0, 0, 0, 0, 1],
                 [0, 0, 1, 0, 0, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0, 0, 0],
                 [1, 0, 1, 0, 1, 0, 0, 0]])

# Función para diagonalizar una matriz y calcular su potencia
def diagonalizar_y_potenciar(A, k, vertices):
    # Encontrar los autovalores y autovectores
    autovalores, autovectores = np.linalg.eig(A)

    # Imprimir autovalores y autovectores
    print("Autovalores:")
    print(autovalores)
    print("\nAutovectores:")
    print(autovectores)

    # Crear la matriz diagonal D con los autovalores
    D = np.diag(autovalores)

    # Invertir la matriz de autovectores
    P_inv = np.linalg.inv(autovectores)

    # Imprimir las matrices de diagonalización
    print("\nMatriz de autovectores (P):")
    print(autovectores)
    print("\nMatriz diagonal de autovalores (D):")
    print(D)
    print("\nMatriz inversa de autovectores (P_inv):")
    print(P_inv)

    # Calcular A^k usando la diagonalización
    D_potencia = np.linalg.matrix_power(D, k)
    A_potencia = autovectores @ D_potencia @ P_inv

    # Imprimir la matriz resultante A^k
    print(f"\nMatriz A^{k}:\n", A_potencia)

    # Devolver el valor específico de la trayectoria solicitada
    i, j = vertices
    return A_potencia[i - 1, j - 1]

# a. Número de 10-trayectorias entre los vértices 2 y 4 de G1
print("\nGrafo G1:")
resultado_G1 = diagonalizar_y_potenciar(A_G1, 10, (2, 4))
print(f"\nEl número de 10-trayectorias entre los vértices 2 y 4 de G1 es: {int(resultado_G1)}")

# b. Número de 13-trayectorias entre los vértices 4 y 5 de G2
print("\nGrafo G2:")
resultado_G2 = diagonalizar_y_potenciar(A_G2, 13, (4, 5))
print(f"\nEl número de 13-trayectorias entre los vértices 4 y 5 de G2 es: {int(resultado_G2)}")

# c. Número de circuitos de longitud 12 del vértice 7 de G3
print("\nGrafo G3:")
resultado_G3 = diagonalizar_y_potenciar(A_G3, 12, (7, 7))
print(f"\nEl número de circuitos de longitud 12 del vértice 7 de G3 es: {int(resultado_G3)}")



Grafo G1:
Autovalores:
[ 2.56155281e+00  4.19213546e-17 -1.56155281e+00 -1.00000000e+00]

Autovectores:
[[-4.35162146e-01 -7.07106781e-01 -5.57345410e-01  1.57009246e-16]
 [-5.57345410e-01  1.26658326e-16  4.35162146e-01 -7.07106781e-01]
 [-4.35162146e-01  7.07106781e-01 -5.57345410e-01  1.57009246e-16]
 [-5.57345410e-01  1.17332908e-17  4.35162146e-01  7.07106781e-01]]

Matriz de autovectores (P):
[[-4.35162146e-01 -7.07106781e-01 -5.57345410e-01  1.57009246e-16]
 [-5.57345410e-01  1.26658326e-16  4.35162146e-01 -7.07106781e-01]
 [-4.35162146e-01  7.07106781e-01 -5.57345410e-01  1.57009246e-16]
 [-5.57345410e-01  1.17332908e-17  4.35162146e-01  7.07106781e-01]]

Matriz diagonal de autovalores (D):
[[ 2.56155281e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  4.19213546e-17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.56155281e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+00]]

Matriz inversa de aut